### PR TITLE
Add macos x86_amd64 11.7 BigSur version

### PR DESCRIPTION
**Pull request by Angluca**
Old macbook use x86_amd64 macos 11.7 ( < 12.x ) BigSur version, Cant install \/ upgrade >= macos 12.x version

### CODE REVIEW

**Comment by floooh** [comment]
Thaks for making me aware of the problem, however: 

Just replacing the executable here won't help, since it will be overwritten next time I'm building new executables via Github Actions (e.g. see https://github.com/floooh/sokol-tools/blob/master/.github/workflows/deploy.yml).

We instead need to fix the CMakeLists.txt file here so that it produces an executable that's compatible with older macOS versions in the sokol-tools cmake file:

https://github.com/floooh/sokol-tools/blob/master/CMakeLists.txt

I think what's missing there is a `CMAKE_OSX_DEPLOYMENT_TARGET` like I did here in the sokol-samples cmake file:

https://github.com/floooh/sokol-samples/blob/74cf3320b61620cd839d5317acbe7c3c2c0f77b6/CMakeLists.txt#L9

I'm closing this PR. Can you maybe experiment with CMAKE_OSX_DEPLOYMENT_TARGET and create a PR in the sokol-tools repo? (unfortunately I don't have a Mac with Big Sur around to test).

This would then also automatically take care of Intel Macs.

(PS: sokol-tools-bin doesn't have universal binaries, but instead it has separate binaries for Intel and ARM Macs, but those are built automatically in the Github Actions script I mentioned above)

**Comment by floooh** [comment]
PS: the path for the amd64 executable should actually be `bin/osx` not `bin/osx_amd64`.

Does the executable that's committed to `bin/osx` work for you? (because on further thinking about it, I don't think that the `CMAKE_OSX_DEPLOYMENT_TARGET` variable should matter for command line tools, but I'm not entirely sure)

**Comment by floooh** [comment]
Note: I just did this change and executables are currently building (I dusted off my old Intel Mac to test and could reproduce the problem there). Still need to test if the fix actually works though.

**Comment by floooh** [comment]
PS: it seems to have worked, the macOS sokol-shdc executable under /bin/osx should now run on older Intel Macs again.

**Comment by Angluca** [comment]
Well! new bin/osx/sokol-shdc can run on old macos now :)

**Pull request closed without merging**
